version: '3.7'

services:
    videogram:
        image: bot-videogram
        hostname: videogram
        environment:
            - TOKEN=${VIDEOGRAM_TOKEN}
        build:
            context: ./
            args:
                - "UID=${UID:-1000}"
                - "GID=${GID:-1000}"
        restart: always
        volumes:
            - ./config:/home/videogram/.config/videogram
