version: '3.7'

services:
    videogram:
        image: bot-videogram
        hostname: videogram
        environment:
            - TOKEN=${VIDEOGRAM_TOKEN}
        build:
            context: ./
        restart: always
        volumes:
            - ./config:/home/videogram/.config/videogram
